name: example
description: A new Flutter project.
version: 1.0.1
publish_to: none

environment:
  # [Original] sdk: ">=2.12.0 <3.0.0"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  # For Dio Kit
  dio: ^5.7.0

  # For get_connect kit
  get: ^4.6.6

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: ^1.16.6

  vm_service: ^14.2.5

  ume:
    path: ../
flutter:
  uses-material-design: true
