name: ume
description: Community Version of UME is an in-app debug kits platform for Flutter apps.
version: 2.0.6
homepage: https://github.com/ume-community/ume
topics: [debug, in-app-debug, diagnostics, plugin, ume]
screenshots:
  - description: "ume logo with transparent background"
    path: ume_logo_256.png

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.0.15

  vm_service: ^15.0.0

  tuple: ^2.0.0

  ume_core: ^2.0.2
  ume_kit_channel_monitor: ^2.0.0
  ume_kit_channel_observer: ^2.0.0
  ume_kit_clean_local_data: ^2.0.0
  ume_kit_console: ^2.0.0
  ume_kit_database: ^2.0.0
  ume_kit_designer_check: ^2.0.0
  ume_kit_device: ^2.0.0
  ume_kit_dio: ^2.0.1
  ume_kit_get_connect: ^2.0.0
  ume_kit_memory_detector: ^2.0.1
  ume_kit_monitor: ^2.0.0
  ume_kit_perf: ^2.0.1
  ume_kit_shared_preferences: ^2.0.0
  ume_kit_show_code: ^2.0.2
  ume_kit_slow_animation: ^2.0.0
  # ume_kit_storage:
  #   path: ./ume_kits/packages/ume_kit_storage
  ume_kit_ui: ^2.0.0

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter
  melos: ^6.2.0
  mockito: ^5.3.2
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65
  # lints: ^5.1.0

flutter:
  uses-material-design: true
