name: ume_kit_shared_preferences_example
resolution: workspace
description: Example app demonstrating the ume_kit_shared_preferences kit.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^2.0.0
  shared_preferences: ^2.0.7

  ume_core: ^2.0.1
  ume_kit_shared_preferences: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
