name: ume_kit_designer_check
resolution: workspace
description: Designer UI check tool for UME.
version: 2.0.2
homepage: https://github.com/insightop/ume/tree/master/packages/ume_kit_designer_check

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2

  ume_core: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
